name: Feature request
description: Suggest an improvement.
title: "[Feature]: "
body:
  - type: textarea
    id: need
    attributes:
      label: What problem should this solve?
      description: Describe the use case with fictional examples.
    validations:
      required: true
  - type: textarea
    id: behavior
    attributes:
      label: Proposed behavior
    validations:
      required: true
